### ISSUE TITLE
How do I change the dev server's port?

### ISSUE THREAD

**Issue by RapidOwl** [marko-js/run#50] opened 2023-08-28 15:33 UTC
Marko runs on port 3000 by default, but (for reasons) my work machine has another service running on that port. Is there a config file that I've not yet created?

I went and looked at the Vite docs. I tried setting it via Vite config, but Marko then errored with `Unable to resolve @marko/run options`.

I've managed to get it working by running `npm run dev -- --port 3123`, but I don't want to have to type that every time.

**Comment by rturnq** [comment] 2023-09-25 23:39
This is fixed in 0.2.5

Previously, the CLI was only respecting `config.preview.port`.

Now when using `dev`, port will be determined by checking the following in this order:
1.  `--port` CLI argument
2. `config.server.port` from the vite.config
3. `config.preview.port` from the vite.config
4. `PORT` environment variable
5. 3000

`preview` will do the same thing but prefer `config.preview.port` over `config.server.port`.

Finally, once the port is resolved and it is already in use by another process, the an available port will be chosen for you. If you always want to use any available port, you can use 0 for your port config (eg. `npm run dev -- --port=0`).

@RapidOwl That error you are seeing `Error: Unable to resolve @marko/run options` is caused by the Marko Run Vite plugin not being specified in your Vite config. In 0.2.5, the CLI will also automatically add the plugin when the Vite config loaded does not specify it. This means you only have to include your overriding options like you were expecting.

**Comment by RapidOwl** [comment] 2023-09-26 14:33
Thank you! This sorted it and I'm now up and running. I really appreciate the detailed explanation.

I was running a much earlier version of `@marko/run` and `npm update` didn't change it. I've explicitly install 0.2.5 and updated my `vite.config.ts`.

**Closed** 2023-09-26 15:36 UTC
